name: Create Flatpak Release Artifact

on:
  workflow_dispatch:

jobs:
  package-yoohoo:
    permissions:
      contents: write
    runs-on: ubuntu-24.04
    container:
      image: ghcr.io/flathub-infra/flatpak-github-actions:gnome-48
      options: --privileged
    steps:
      - uses: actions/checkout@v4

      - name: Update Flatpak Source Lists
        run: |
          dnf install -y gcc gcc-c++ make python3 pipx python3-tomlkit python3-aiohttp wget

          pipx install git+https://github.com/flatpak/flatpak-builder-tools.git#subdirectory=node
          wget https://raw.githubusercontent.com/flatpak/flatpak-builder-tools/refs/heads/master/cargo/flatpak-cargo-generator.py -O ~/flatpak-cargo-generator.py

          python3 ~/flatpak-cargo-generator.py -o download-sources/cargo.json ./src-tauri/Cargo.lock
          sed -i 's/"dest": "c/"dest": "src-tauri\/c/g' download-sources/cargo.json
          flatpak-node-generator yarn -o download-sources/yarn.json yarn.lock

      - uses: flatpak/flatpak-github-actions/flatpak-builder@v6
        with:
          bundle: yoohoo.flatpak
          manifest-path: dev.shob3r.yoohoo.yml
          cache-key: flatpak-builder-${{ github.sha }}
          branch: main
