name: Update Node/Cargo Flatpak Sources
on:
  push:
  workflow_dispatch:

jobs:
  update-sources:
    permissions:
      contents: write
    runs-on: "ubuntu-24.04"
    steps:
      - uses: actions/checkout@v4

      # You don't need NodeJS or Cargo here, since no packages are being installed.
      - name: Install Dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y build-essential python3 pipx

      - name: Generate Sources
        run: |
          pipx run flatpak-cargo-generator -o download-sources/cargo.json ./src-tauri/Cargo.lock
          sed -i 's/"dest": "c/"dest": "src-tauri\/c/g' download-sources/cargo.json
