name: Update Node/Cargo Flatpak Builder Sources
on:
  push:
    paths:
      - "package.json"
      - "yarn.lock"
      - "src-tauri/Cargo.toml"
      - "src-tauri/Cargo.lock"
    branches:
      - main
  workflow_dispatch:

jobs:
  update-flatpak-download-sources:
    permissions:
      contents: write
      pull-requests: write
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v6
        with:
          token: ${{ secrets.FLATPAK_UPDATE_KEY }}

      - name: Set up Node.js
        uses: actions/setup-node@v6
        with:
          node-version: 24
      
      - name: Install UV
        uses: astral-sh/setup-uv@08807647e7069bb48b6ef5acd8ec9567f424441b # V8.1.0 (Latest as of writing)

      - name: Install Python & Python Dependencies
        run: |
          uv python install
          uv tool install "flatpak-node-generator @ git+https://github.com/flatpak/flatpak-builder-tools.git#subdirectory=node"
      - name: Generate Sources
        run: |
          curl -s https://raw.githubusercontent.com/flatpak/flatpak-builder-tools/refs/heads/master/cargo/flatpak-cargo-generator.py | uv run --with tomlkit - -o download-sources/cargo.json ./src-tauri/Cargo.lock          sed -i 's/"dest": "c/"dest": "src-tauri\/c/g' download-sources/cargo.json
          flatpak-node-generator yarn -o download-sources/yarn.json yarn.lock
          node scripts/gen-corepack.ts

      - name: Commit and push changes
        run: |
          git config --global user.name 'github-actions[bot]'
          git config --global user.email 'github-actions[bot]@users.noreply.github.com'
          git add --all
          git diff-index --quiet HEAD || git commit -m "Update Flatpak download sources"
          git push origin HEAD:main
